# Generated by Django 6.0.4 on 2026-04-22 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_founder_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or emoji', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
